//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apa_pack
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATRAGE
    {
        public short CATRAGE_ID { get; set; }
        public string USER_NAME { get; set; }
        public Nullable<System.DateTime> CFD_1 { get; set; }
        public Nullable<System.DateTime> ED_1 { get; set; }
        public Nullable<System.DateTime> CFD_2 { get; set; }
        public Nullable<System.DateTime> ED_2 { get; set; }
        public Nullable<System.DateTime> CFD_3 { get; set; }
        public Nullable<System.DateTime> ED_3 { get; set; }
        public short PRINTERS_ID { get; set; }
    
        public virtual Printer Printer { get; set; }
    }
}
