//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apa_pack
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPUTER
    {
        public int COM_ID { get; set; }
        public string COMPUTER_NAME { get; set; }
        public string PROCESSOR { get; set; }
        public string SYSTEM_TYPE { get; set; }
        public string RAM { get; set; }
        public string SYSTEM_MANUFACTURE { get; set; }
        public string SYSTEM_MODEL { get; set; }
        public string GRAFIC_CARD { get; set; }
        public string OPRATING_SYSTEM { get; set; }
        public string LOCATIONS { get; set; }
        public string USER_NAME { get; set; }
        public string PASSWORD { get; set; }
        public string MONITOR { get; set; }
        public string UPS { get; set; }
        public string KEYBOARD_MOUSE { get; set; }
        public string MICRO_USB_ADAPTER { get; set; }
    }
}
