<%
Sub srnoAlert ()
response.write "<table id='tbdhead' width='100%'  border='0' cellspacing='0' cellpadding='0'>"
  response.write "<tr>"
    response.write "<td align='center' valign='middle'>&nbsp;</td>"
 response.write " </tr>"
  response.write "<tr>"
   response.write " <td align='center' valign='middle'><table width='50%'  border='0' cellpadding='0' cellspacing='0' class='alert_bg_blue'>"
     response.write " <tr>"
      response.write "  <td align='center' valign='middle'><table border='0' cellspacing='0' cellpadding='0' width='435'>"
       response.write "     <tr>"
      response.write "        <td align='left' valign='middle' width='128'><img src='images/attention.png' width='128' height='128'></td>"
         response.write "     <td align='left' valign='middle' width='303'><span class='bodytxt_black_b'><font size='+2'>Select the above</font></span><span class='bodytxt_red_b'><font size='+2'> SRN No</font></span></td>"
         response.write "   </tr>"
      response.write "  </table></td>"
     response.write " </tr>"
   response.write " </table></td>"
  response.write "</tr>"
response.write "</table>"
end sub

Sub bankAlert ()
response.write "<table id='tbdhead' width='100%'  border='0' cellspacing='0' cellpadding='0'>"
  response.write "<tr>"
    response.write "<td align='center' valign='middle'>&nbsp;</td>"
 response.write " </tr>"
  response.write "<tr>"
   response.write " <td align='center' valign='middle'><table width='50%'  border='0' cellpadding='0' cellspacing='0' class='alert_bg_blue'>"
     response.write " <tr>"
      response.write "  <td align='center' valign='middle'><table border='0' cellspacing='0' cellpadding='0' width='435'>"
       response.write "     <tr>"
      response.write "        <td align='left' valign='middle' width='128'><img src='images/attention.png' width='128' height='128'></td>"
         response.write "     <td align='left' valign='middle' width='303'><span class='bodytxt_black_b'><font size='+2'>Select the above</font></span><span class='bodytxt_red_b'><font size='+2'> Bank</font></span></td>"
         response.write "   </tr>"
      response.write "  </table></td>"
     response.write " </tr>"
   response.write " </table></td>"
  response.write "</tr>"
response.write "</table>"
end sub

Sub ATMAlert ()
response.write "<table id='tbdhead' width='100%'  border='0' cellspacing='0' cellpadding='0'>"
  response.write "<tr>"
    response.write "<td align='center' valign='middle'>&nbsp;</td>"
 response.write " </tr>"
  response.write "<tr>"
   response.write " <td align='center' valign='middle'><table width='50%'  border='0' cellpadding='0' cellspacing='0' class='alert_bg_blue'>"
     response.write " <tr>"
      response.write "  <td align='center' valign='middle'><table border='0' cellspacing='0' cellpadding='0' width='435'>"
       response.write "     <tr>"
      response.write "        <td align='left' valign='middle' width='128'><img src='images/attention.png' width='128' height='128'></td>"
         response.write "     <td align='left' valign='middle' width='303'><span class='bodytxt_black_b'><font size='+2'>Select the above</font></span><span class='bodytxt_red_b'><font size='+2'> ATM ID</font></span></td>"
         response.write "   </tr>"
      response.write "  </table></td>"
     response.write " </tr>"
   response.write " </table></td>"
  response.write "</tr>"
response.write "</table>"
end sub

Sub ResolutionAlert ()
response.write "<table id='tbdhead' width='100%'  border='0' cellspacing='0' cellpadding='0'>"
  response.write "<tr>"
    response.write "<td align='center' valign='middle'>&nbsp;</td>"
 response.write " </tr>"
  response.write "<tr>"
   response.write " <td align='center' valign='middle'><table width='50%'  border='0' cellpadding='0' cellspacing='0' class='alert_bg_blue'>"
     response.write " <tr>"
      response.write "  <td align='center' valign='middle'><table border='0' cellspacing='0' cellpadding='0' width='435'>"
       response.write "     <tr>"
      response.write "        <td align='left' valign='middle' width='128'><img src='images/attention.png' width='128' height='128'></td>"
         response.write "     <td align='left' valign='middle' width='303'><span class='bodytxt_black_b'><font size='+2'>Select the above</font></span><span class='bodytxt_red_b'><font size='+2'> Resolution</font></span></td>"
         response.write "   </tr>"
      response.write "  </table></td>"
     response.write " </tr>"
   response.write " </table></td>"
  response.write "</tr>"
response.write "</table>"
end sub

Sub DefectAlert ()
response.write "<table id='tbdhead' width='100%'  border='0' cellspacing='0' cellpadding='0'>"
  response.write "<tr>"
    response.write "<td align='center' valign='middle'>&nbsp;</td>"
 response.write " </tr>"
  response.write "<tr>"
   response.write " <td align='center' valign='middle'><table width='50%'  border='0' cellpadding='0' cellspacing='0' class='alert_bg_blue'>"
     response.write " <tr>"
      response.write "  <td align='center' valign='middle'><table border='0' cellspacing='0' cellpadding='0' width='435'>"
       response.write "     <tr>"
      response.write "        <td align='left' valign='middle' width='128'><img src='images/attention.png' width='128' height='128'></td>"
         response.write "     <td align='left' valign='middle' width='303'><span class='bodytxt_black_b'><font size='+2'>Select the above</font></span><span class='bodytxt_red_b'><font size='+2'> Defect</font></span></td>"
         response.write "   </tr>"
      response.write "  </table></td>"
     response.write " </tr>"
   response.write " </table></td>"
  response.write "</tr>"
response.write "</table>"
end sub

Sub actAlert ()
response.write "<table id='tbdhead' width='100%'  border='0' cellspacing='0' cellpadding='0'>"
  response.write "<tr>"
    response.write "<td align='center' valign='middle'>&nbsp;</td>"
 response.write " </tr>"
  response.write "<tr>"
   response.write " <td align='center' valign='middle'><table width='50%'  border='0' cellpadding='0' cellspacing='0' class='alert_bg_blue'>"
     response.write " <tr>"
      response.write "  <td align='center' valign='middle'><table border='0' cellspacing='0' cellpadding='0' width='435'>"
       response.write "     <tr>"
      response.write "        <td align='left' valign='middle' width='128'><img src='images/attention.png' width='128' height='128'></td>"
         response.write "     <td align='left' valign='middle' width='303'><span class='bodytxt_black_b'><font size='+2'>Select the above</font></span><span class='bodytxt_red_b'><font size='+2'>Activity</font></span></td>"
         response.write "   </tr>"
      response.write "  </table></td>"
     response.write " </tr>"
   response.write " </table></td>"
  response.write "</tr>"
response.write "</table>"
end sub

%>